### ISSUE TITLE
Page not rendering well

### ISSUE THREAD

**Issue by rcortes100** [melvinchng/event-jekyll-theme#9]
Hi! I wanted to use this nice template for a conference webpage. I already forked the project, but it is not rendering the webpage properly. Any tip or advice would be helpful to make it work with Github Pages.

**Comment by melvinchng** [comment]
The expected URL to your page is YOUR_GITHUB_USERNAME.github.io. If you forked the project, you are expecting the URL to be YOUR_GITHUB_USERNAME.github.io/YOUR_PROJECT_NAME. In this case, you have to change your asset path and baseurl in config.yml and the head section. You can try to right click and inspect which CSS asset is having issue and resolve the CSS asset from there.

**Comment by HuangJunye** [comment]
@melvinchng Thanks for the explanation. I have the exact problem. Will figure out how to do for a forked project. What if I am using a custom domain name, for example www.xxx.com? What do I need to change?

**Comment by melvinchng** [comment]
> @melvinchng Thanks for the explanation. I have the exact problem. Will figure out how to do for a forked project. What if I am using a custom domain name, for example [www.xxx.com](http://www.xxx.com)? What do I need to change?

It's very easy and straight forward. I don't remember if you need a paid GitHub account for that. Refer here: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by HuangJunye** [comment]
Thanks for the reference. I will try it out!
